// @ts-nocheck

import {writable} from 'svelte/store';
export const tasklist = writable([
    {
        "id": 1,
        "title": "Проектш Alpha",
        "start": "2023-05-15",
        "finish": "2023-09-30",
        "finished": "2023-12-28",
        "deadline": "",
        "category": "Разработка ПО",
        "status": "done",
        "importance": 1,
        "type": "standard", 
            // standard - обычная задача
            // vector - задача только для векторов
    },
    {
        "id": 2,
        "title": "w".repeat(50),
        "start": "2023-07-01",
        "finish": "2023-12-31",
        "finished": "2023-12-28",
        "deadline": "2024-03-12 15:15",
        "category": "Маркетинг",
        "status": "done",
        "importance": 1,
        "type": "standard",
    },
    {
        "id": 3,
        "title": "Обновление инфраштруктуры",
        "start": "2023-03-01",
        "finish": "2023-07-15",
        "finished": "",
        "deadline": "",
        "category": "ИТ",
        "status": "wait",
        "importance": 2,
        "type": "standard",
    },
    {
        "id": 4,
        "title": "Исследование рынка",
        "start": "2023-09-01",
        "finish": "2023-11-30",
        "finished": "",
        "deadline": "2024-03-12 15:15",
        "category": "Аналитика",
        "status": "wait",
        "importance": 2,
        "type": "standard",
    },
    {
        "id": 5,
        "title": "Тренинг для сотрудников",
        "start": "2023-06-01",
        "finish": "2023-06-30",
        "finished": "",
        "deadline": "2024-03-12 15:15",
        "category": "Обучение",
        "status": "wait",
        "importance": 2,
        "type": "standard",
    },
    {
        "id": 6,
        "title": "Разработка мобильного приложения",
        "start": "2023-04-01",
        "finish": "2023-10-31",
        "finished": "2023-12-28",
        "deadline": "2024-03-12 15:50",
        "category": "Разработка ПО",
        "status": "fail",
        "importance": 2,
        "type": "standard",
    },
    {
        "id": 7,
        "title": "Запуск рекламной кампании",
        "start": "2023-08-15",
        "finish": "2023-11-15",
        "finished": "",
        "deadline": "2024-03-12 15:50",
        "category": "Маркетинг",
        "status": "wait",
        "importance": 3,
        "type": "standard",
    },
    {
        "id": 8,
        "title": "Модернизация серверов",
        "start": "2023-02-01",
        "finish": "2023-05-31",
        "finished": "",
        "deadline": "2024-03-12 15:50",
        "category": "ИТ",
        "status": "wait",
        "importance": 3,
        "type": "standard",
    },
    {
        "id": 9,
        "title": "Анализ конкурентов",
        "start": "2023-07-01",
        "finish": "2023-09-30",
        "finished": "",
        "deadline": "2024-03-12 15:50",
        "category": "Аналитика",
        "status": "wait",
        "importance": 3,
        "type": "standard",
    },
    {
        "id": 10,
        "title": "Курс по продажам",
        "start": "2023-08-01",
        "finish": "2023-08-31",
        "finished": "",
        "deadline": "2024-03-12 15:50",
        "category": "Обучение",
        "status": "wait",
        "importance": 0,
        "type": "standard",
    },
    {
        "id": 11,
        "title": "Проект Beta",
        "start": "2023-06-01",
        "finish": "2023-11-30",
        "finished": "",
        "deadline": "2024-03-12 15:50",
        "category": "Разработка ПО",
        "status": "wait",
        "importance": 0,
        "type": "standard",
    },
    {
        "id": 12,
        "title": "Продвижение в социальных сетях",
        "start": "2023-09-01",
        "finish": "2023-12-31",
        "finished": "2023-12-28",
        "deadline": "2024-03-12 15:50",
        "category": "Маркетинг",
        "status": "done",
        "importance": 0,
        "type": "standard",
    },
    {
        "id": 13,
        "title": "Внедрение системы безопасности",
        "start": "2023-04-01",
        "finish": "2023-07-31",
        "finished": "",
        "deadline": "2024-03-12 15:50",
        "category": "ИТ",
        "status": "wait",
        "importance": 2,
        "type": "standard",
    },
    {
        "id": 14,
        "title": "Опрос клиентов",
        "start": "2023-10-01",
        "finish": "2023-11-15",
        "finished": "",
        "deadline": "2024-03-12 15:50",
        "category": "Аналитика",
        "status": "wait",
        "importance": 1,
        "type": "standard",
    },
    {
        "id": 15,
        "title": "Тренинг по эффективным коммуникациям",
        "start": "2023-07-01",
        "finish": "2023-07-31",
        "finished": "",
        "deadline": "2024-03-12 15:50",
        "category": "Обучение",
        "status": "wait",
        "importance": 3,
        "type": "standard",
    },
    {
        "id": 16,
        "title": "Проект Gamma",
        "start": "2023-03-01",
        "finish": "2023-09-30",
        "finished": "",
        "deadline": "2024-03-12 15:50",
        "category": "Разработка ПО",
        "status": "wait",
        "importance": 2,
        "type": "standard",
    },
    {
        "id": 17,
        "title": "Запуск email-рассылки",
        "start": "2023-06-01",
        "finish": "2023-08-31",
        "finished": "",
        "deadline": "2024-03-12 15:50",
        "category": "Маркетинг",
        "status": "wait",
        "importance": 2,
        "type": "standard",
    },
    {
        "id": 18,
        "title": "Обновление сетевого оборудования",
        "start": "2023-05-01",
        "finish": "2023-08-15",
        "finished": "",
        "deadline": "2024-03-12 15:50",
        "category": "ИТ",
        "status": "wait",
        "importance": 1,
        "type": "standard",
    },
    {
        "id": 19,
        "title": "Анализ удовлетворенности клиентов",
        "start": "2023-11-01",
        "finish": "2023-12-31",
        "finished": "2023-12-28",
        "deadline": "2024-03-12 15:50",
        "category": "Аналитика",
        "status": "done",
        "importance": 1,
        "type": "standard",
    },
    {
        "id": 20,
        "title": "Тренинг по управлению временем",
        "start": "2023-09-01",
        "finish": "2023-09-30",
        "finished": "",
        "deadline": "2024-03-12 15:50",
        "category": "Обучение",
        "status": "wait",
        "importance": 1,
        "type": "standard",
    },
    {
        "id": 21,
        "title": "Проект Delta",
        "start": "2023-07-01",
        "finish": "2024-02-28",
        "finished": "",
        "deadline": "2024-03-12 15:50",
        "category": "Разработка ПО",
        "status": "wait",
        "importance": 1,
        "type": "standard",
    },
    {
        "id": 22,
        "title": "Организация выставки",
        "start": "2023-10-01",
        "finish": "2023-11-30",
        "finished": "",
        "deadline": "2024-03-12 15:50",
        "category": "Маркетинг",
        "status": "wait",
        "importance": 1,
        "type": "standard",
    },
    {
        "id": 23,
        "title": "Развертывание облачной инфраструктуры",
        "start": "2023-06-01",
        "finish": "2023-10-31",
        "finished": "",
        "deadline": "2024-03-12 15:50",
        "category": "ИТ",
        "status": "wait",
        "importance": 2,
        "type": "standard",
    },
    {
        "id": 24,
        "title": "Изучение потребительских предпочтений",
        "start": "2023-08-01",
        "finish": "2023-10-15",
        "finished": "2023-12-28",
        "deadline": "2024-03-12 15:50",
        "category": "Аналитика",
        "status": "fail",
        "importance": 3,
        "type": "standard",
    },
    {
        "id": 25,
        "title": "Тренинг по лидерству",
        "start": "2023-11-01",
        "finish": "2023-11-30",
        "finished": "",
        "deadline": "2024-03-12 15:50",
        "category": "Обучение",
        "status": "wait",
        "importance": 0,
        "type": "standard",
    },
    {
        "id": 26,
        "title": "Тренинг по управлению временем",
        "start": "2023-09-01",
        "finish": "2023-09-30",
        "finished": "",
        "deadline": "2024-03-12 15:50",
        "category": "Обучение",
        "status": "wait",
        "importance": 0,
        "type": "standard",
    },
    {
        "id": 27,
        "title": "Проект Delta",
        "start": "2023-07-01",
        "finish": "2024-02-28",
        "finished": "",
        "deadline": "2024-03-12 15:50",
        "category": "Разработка ПО",
        "status": "wait",
        "importance": 0,
        "type": "standard",
    },
    {
        "id": 28,
        "title": "Организация выставки",
        "start": "2023-10-01",
        "finish": "2023-11-30",
        "finished": "",
        "deadline": "2024-03-12 15:50",
        "category": "Маркетинг",
        "status": "wait",
        "importance": 0,
        "type": "standard",
    },
    {
        "id": 29,
        "title": "Развертывание облачной инфраструктуры",
        "start": "2023-06-01",
        "finish": "2023-10-31",
        "finished": "",
        "deadline": "2024-03-12 15:50",
        "category": "ИТ",
        "status": "wait",
        "importance": 2,
        "type": "standard",
    },
    {
        "id": 30,
        "title": "Изучение потребительских предпочтений",
        "start": "2023-08-01",
        "finish": "2023-10-15",
        "finished": "2023-12-28",
        "deadline": "2024-03-12 15:50",
        "category": "Аналитика",
        "status": "fail",
        "importance": 1,
        "type": "standard",
    },
    {
        "id": 31,
        "title": "Тренинг по лидерству",
        "start": "2023-11-01",
        "finish": "2023-11-30",
        "finished": "",
        "deadline": "2024-03-12 15:50",
        "category": "Обучение",
        "status": "wait",
        "importance": 3,
        "type": "standard",
    }
]);


export let allCategories = [];
tasklist.subscribe(items => {
    items.forEach(item => {
        if (!allCategories.includes(item.category))
            allCategories.push(item.category)
    })
});


export let per100 = writable([
    undefined
])

export let per200 = writable([
    undefined,
    undefined,
    undefined
])

export let per300 = writable([
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
])


export let vectors = writable([])

